version: "3.9"

services:
  maven-build:
    image: maven:3.9.10-eclipse-temurin-17
    container_name: maven-build
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2   

    command: mvn clean install
